project:
  type: book
  output-dir: docs

book:
  title: "Data analysis with Programming"
  author: "Jonas Moss"
  date: "12.12.2022"
  search: false
  repo-url: https://github.com/bi-ds/EBA-3500/
  sidebar:
    style: floating
  chapters:
    - index.qmd
    - site/00-python-tips.qmd
    - site/01-scipy-numpy.qmd
    - site/02-statistical-simulation.qmd
    - site/03-exploratory-data-analysis.qmd
    - site/04-statistical-models.qmd
    - site/05-unbiased-estimators-efficiency.qmd
    - site/06-constructing-estimators.qmd
    - site/07-confidence-intervals.qmd
    - site/08-testing-hypotheses.qmd
    - site/09-testing-the-sample-mean.qmd
    - site/10-statistical-learning.qmd
    - site/11-basics-of-linear-regression.qmd
    - site/12-inference-for-linear-regression.qmd
    - site/14-binary-regression.qmd

format:
  html:
    theme: simplex
    highlight-style: atom-one

editor: source
execute:
  cache: true
  enabled: true
  output: true
  freeze: auto
jupyter: python3
